spring:
  application:
    name: lottery-system
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/lottery_db?useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}
      minimum-idle: ${DB_MIN_IDLE:5}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    lettuce:
      pool:
        max-active: ${REDIS_POOL_MAX_ACTIVE:20}
        max-idle: ${REDIS_POOL_MAX_IDLE:10}
        min-idle: ${REDIS_POOL_MIN_IDLE:5}

  cache:
    type: redis
    redis:
      time-to-live: 3600000

jwt:
  secret: ${JWT_SECRET:yourSecretKeyForJWTTokenGeneration}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    root: INFO
    com.lottery: ${LOG_LEVEL:DEBUG}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html